#docker run -d --rm -name sqlserver -p 1433:1433 
#docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=123" --name sqlserver2 -p 1431:1433 -d mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04


version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
    container_name: sqlserver2
    environment:
       ACCEPT_EULA: "Y"
       SA_PASSWORD: "P@ssw0rd"
    ports:
      - 1431:1433
  redis:
    image: redis
    container_name: rediserver   
    ports:
      - 6379:6379
   